#!/usr/bin/expect -f

set timeout 60
set mnemonic [lindex $argv 0]
set passphrase [lindex $argv 1]

set home_dir "$env(HOME)/sentinel-dvpncli"

spawn sentinel-dvpncli keys add main --keyring.backend test --home $home_dir

expect "Enter mnemonic*"
send "$mnemonic\r"

expect "Enter your BIP-39 passphrase*"
send "\r"

expect "Enter keyring passphrase*"
send "$passphrase\r"

expect "Enter keyring passphrase again*"
send "$passphrase\r"

expect eof